//! Writing blocks as body text.

use super::parse::parse_para_open;
use super::{
    Block, EMPTY_LINE, EMPTY_PARAGRAPH, Inline, Mark, PARA_CLOSE, ParaAttrs, SCENE_BREAK_LINE,
    Toggles, starts_with,
};

/// Writes blocks as body text. The result ends with a newline unless empty.
pub fn write_body(blocks: &[Block]) -> String {
    let mut out = String::new();
    for (i, block) in blocks.iter().enumerate() {
        if i > 0 {
            out.push_str("\n\n");
        }
        match block {
            Block::SceneBreak {} => out.push_str(SCENE_BREAK_LINE),
            Block::Paragraph { attrs, content } => out.push_str(&write_paragraph(*attrs, content)),
        }
    }
    if !out.is_empty() {
        out.push('\n');
    }
    out
}

pub(super) enum Run {
    Text(String, Vec<Mark>),
    Break,
}

/// Merges neighbouring text with the same marks, turns stray newlines into line
/// breaks and drops empty text.
pub(super) fn runs(content: &[Inline]) -> Vec<Run> {
    let mut out: Vec<Run> = Vec::new();
    for inline in content {
        match inline {
            Inline::HardBreak {} => out.push(Run::Break),
            Inline::Text { text, marks } => {
                let mut marks = marks.clone();
                marks.sort();
                marks.dedup();
                for (i, part) in text.replace('\r', "").split('\n').enumerate() {
                    if i > 0 {
                        out.push(Run::Break);
                    }
                    if part.is_empty() {
                        continue;
                    }
                    match out.last_mut() {
                        Some(Run::Text(prev, prev_marks)) if *prev_marks == marks => {
                            prev.push_str(part)
                        }
                        _ => out.push(Run::Text(part.to_string(), marks.clone())),
                    }
                }
            }
        }
    }
    out
}

enum Tok<'a> {
    Text(&'a str),
    Markup(String),
    Break,
}

impl Toggles {
    fn from_marks(marks: &[Mark]) -> Self {
        Toggles {
            strike: marks.contains(&Mark::Strike {}),
            bold: marks.contains(&Mark::Bold {}),
            italic: marks.contains(&Mark::Italic {}),
        }
    }

    /// Emits the toggles that change towards `want`, only those turning on
    /// (`on == true`) or only those turning off.
    fn change(&mut self, want: Toggles, on: bool, toks: &mut Vec<Tok>) {
        let mut order = [
            (&mut self.strike, want.strike, "~~"),
            (&mut self.bold, want.bold, "**"),
            (&mut self.italic, want.italic, "*"),
        ];
        if !on {
            order.reverse();
        }
        for (state, target, marker) in order {
            if *state != target && target == on {
                *state = target;
                toks.push(Tok::Markup(marker.to_string()));
            }
        }
    }
}

fn open_tag(mark: &Mark) -> String {
    match mark {
        Mark::Memo { attrs } => format!("<mark data-memo=\"{}\">", memo_id(&attrs.id)),
        Mark::Underline {} => "<u>".into(),
        Mark::Dot {} => "<span class=\"dot\">".into(),
        _ => unreachable!("not a tag mark"),
    }
}

fn close_tag(mark: &Mark) -> String {
    match mark {
        Mark::Memo { .. } => "</mark>".into(),
        Mark::Underline {} => "</u>".into(),
        Mark::Dot {} => "</span>".into(),
        _ => unreachable!("not a tag mark"),
    }
}

/// Memo ids are generated by the app; keep only characters that are safe
/// inside the attribute.
fn memo_id(id: &str) -> String {
    id.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .take(64)
        .collect()
}

fn para_open(attrs: ParaAttrs) -> String {
    let mut tag = String::from("<p");
    if attrs.left > 0 {
        tag.push_str(&format!(" data-left=\"{}\"", attrs.left));
    }
    if attrs.right > 0 {
        tag.push_str(&format!(" data-right=\"{}\"", attrs.right));
    }
    if let Some(indent) = attrs.indent {
        tag.push_str(&format!(" data-indent=\"{indent}\""));
    }
    tag.push('>');
    tag
}

fn write_paragraph(attrs: ParaAttrs, content: &[Inline]) -> String {
    let text = paragraph_text(content);
    if !attrs.is_plain() {
        let inner = if text == EMPTY_PARAGRAPH { "" } else { &text };
        return format!("{}{inner}{PARA_CLOSE}", para_open(attrs));
    }
    // Text that would read as the margin tag stays text.
    if parse_para_open(&text.chars().collect::<Vec<_>>()).is_some() {
        format!("\\{text}")
    } else {
        text
    }
}

fn paragraph_text(content: &[Inline]) -> String {
    let runs = runs(content);
    if runs.is_empty() {
        return EMPTY_PARAGRAPH.to_string();
    }
    let mut toks: Vec<Tok> = Vec::new();
    let mut on = Toggles::default();
    let mut tags: Vec<Mark> = Vec::new();
    for run in &runs {
        match run {
            Run::Break => toks.push(Tok::Break),
            Run::Text(text, marks) => {
                let want = Toggles::from_marks(marks);
                let want_tags: Vec<&Mark> = marks.iter().filter(|m| m.is_tag()).collect();
                on.change(want, false, &mut toks);
                let keep = tags
                    .iter()
                    .zip(&want_tags)
                    .take_while(|(a, b)| a == *b)
                    .count();
                while tags.len() > keep {
                    let mark = tags.pop().expect("len > keep");
                    toks.push(Tok::Markup(close_tag(&mark)));
                }
                for mark in &want_tags[keep..] {
                    toks.push(Tok::Markup(open_tag(mark)));
                    tags.push((*mark).clone());
                }
                on.change(want, true, &mut toks);
                toks.push(Tok::Text(text));
            }
        }
    }
    on.change(Toggles::default(), false, &mut toks);
    while let Some(mark) = tags.pop() {
        toks.push(Tok::Markup(close_tag(&mark)));
    }

    let rendered = render(&toks);
    let text = rendered
        .split('\n')
        .map(|line| if line.is_empty() { EMPTY_LINE } else { line })
        .collect::<Vec<_>>()
        .join("\n");
    if text == EMPTY_PARAGRAPH {
        format!("\\{text}")
    } else {
        text
    }
}

fn render(toks: &[Tok]) -> String {
    let mut out = String::new();
    for (i, tok) in toks.iter().enumerate() {
        match tok {
            Tok::Markup(s) => out.push_str(s),
            Tok::Break => out.push('\n'),
            Tok::Text(text) => {
                let next_after = toks.get(i + 1).and_then(|t| match t {
                    Tok::Markup(s) => s.chars().next(),
                    Tok::Text(s) => s.chars().next(),
                    Tok::Break => Some('\n'),
                });
                escape_into(text, next_after, &mut out);
            }
        }
    }
    out
}

fn escape_into(text: &str, next_after: Option<char>, out: &mut String) {
    let chars: Vec<char> = text.chars().collect();
    for (i, &c) in chars.iter().enumerate() {
        let next = chars.get(i + 1).copied().or(next_after);
        match c {
            '\\' => out.push_str("\\\\"),
            '*' => out.push_str("\\*"),
            '~' if next == Some('~') => out.push_str("\\~"),
            '<' if looks_like_tag(&chars[i + 1..]) => out.push_str("\\<"),
            _ => out.push(c),
        }
    }
}

/// Whether the text after a `<` could be read as one of our tags.
fn looks_like_tag(rest: &[char]) -> bool {
    const STARTS: [&str; 6] = ["u>", "/u>", "span", "/span>", "mark", "/mark>"];
    STARTS.iter().any(|s| starts_with(rest, s))
}
